name: LLM Regression Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS CLI 
      run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

    - name: Fetch Public IP
      id: fetch-ip
      run: |
        echo "::set-output name=my_ip::$(curl -s https://api.ipify.org)"
      
    - name: Authorize Security Group Ingress
      run: |
        aws ec2 authorize-security-group-ingress --group-id sg-02a10b5d2f02e077c --protocol tcp --port 11434 --cidr "${{ steps.fetch-ip.outputs.my_ip }}/32" --output text
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/Demogorgon24242/deepeval_open.git
        pip install mlflow pandas ollama flask pymongo

    - name: Run extractor.py
      run: |
        python extractor.py

    - name: Run bot.py
      run: |
        python bot.py

    - name: Run deepeval test_bias.py
      run: |
        deepeval test run test_bias.py -i

    - name: Run deepeval test_coherence.py 
      run: |
        deepeval test run test_coherence.py -i

    - name: Run deepeval test_injection.py 
      run: |
        deepeval test run test_injection.py -i

    - name: Run deepeval test_toxicity.py 
      run: |
        deepeval test run test_toxicity.py -i
